В сервис gateway добавлен сваггер и настроена агрегация спецификаций

diff --git a/compose.yml b/compose.yml
--- a/compose.yml
+++ b/compose.yml
@@ -19,11 +19,11 @@ services:
       retries: 5
       start_period: 10s
     restart: unless-stopped
-    deploy:
-      resources:
-        limits:
-          cpus: '4'
-          memory: 4G
+#    deploy:
+#      resources:
+#        limits:
+#          cpus: '1'
+#          memory: 1G
     networks:
       - memowave-network
 
@@ -46,60 +46,50 @@ services:
       postgres:
         condition: service_healthy # Ensure DB is ready before Liquibase runs
 
-  pgadmin:
-    container_name: memowave_pgadmin_container
-    image: dpage/pgadmin4:latest
-    environment:
-      PGADMIN_DEFAULT_EMAIL: "admin@mail.me"
-      PGADMIN_DEFAULT_PASSWORD: "admin"
-      PGADMIN_CONFIG_SERVER_MODE: "False"
-    healthcheck:
-      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:80/misc/ping || exit -1" ]
-      interval: 10s
-      timeout: 5s
-      start_period: 10s
-      retries: 5
-    volumes:
-      - pgadmin-data:/var/lib/pgadmin
-    ports:
-      - "5050:80"
-    restart: unless-stopped
-    deploy:
-      resources:
-        limits:
-          cpus: '0.5'
-          memory: 1G
-    networks:
-      - memowave-network
-    depends_on:
-      postgres:
-        condition: service_healthy # Ensure DB is ready before Liquibase runs
+#  pgadmin:
+#    container_name: memowave_pgadmin_container
+#    image: dpage/pgadmin4:latest
+#    environment:
+#      PGADMIN_DEFAULT_EMAIL: "admin@mail.me"
+#      PGADMIN_DEFAULT_PASSWORD: "admin"
+#      PGADMIN_CONFIG_SERVER_MODE: "False"
+#    healthcheck:
+#      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:80/misc/ping || exit -1" ]
+#      interval: 10s
+#      timeout: 5s
+#      start_period: 10s
+#      retries: 5
+#    volumes:
+#      - pgadmin-data:/var/lib/pgadmin
+#    ports:
+#      - "5050:80"
+#    restart: unless-stopped
+#    deploy:
+#      resources:
+#        limits:
+#          cpus: '0.5'
+#          memory: 1G
+#    networks:
+#      - memowave-network
+#    depends_on:
+#      postgres:
+#        condition: service_healthy # Ensure DB is ready before Liquibase runs
 
   userservice:
     container_name: user-management-service
     build:
-      dockerfile: module-user-management/Dockerfile
-#      dockerfile_inline: |
-#        # Родительский образ контейнера с gradle внутри
-#        FROM gradle:jdk21-alpine AS build
-#        LABEL authors="viktor"
-#        COPY . /app
-#        WORKDIR /app
-#        RUN gradle clean build --no-daemon
-#
-#        # Родительский образ контейнера с java внутри
-#        FROM eclipse-temurin:21-jre-alpine-3.22 AS run
-#        LABEL authors="viktor"
-#        RUN mkdir /app
-#        WORKDIR /app
-#        # Копирование jar-файла в контейнер
-#        COPY --from=build /app/module-user-management/build/libs/*-0.0.1-SNAPSHOT.jar /app.jar
-#        RUN apk add --no-cache curl
-#        # Открытие порта 8081
-#        EXPOSE 8081
-#        USER 1000:1000
-#        # Команда, которая будет запущена при старте контейнера java -jar ./app.jar
-#        ENTRYPOINT ["java", "-jar", "/app.jar"]
+      dockerfile_inline: |
+        # Родительский образ контейнера с java внутри
+        FROM eclipse-temurin:21-jre-alpine
+        RUN mkdir /app
+        WORKDIR /app
+        # Копирование jar-файла в контейнер
+        COPY module-user-management/build/libs/*-0.0.1-SNAPSHOT.jar /app.jar
+        # Открытие порта 8081
+        EXPOSE 8081
+        USER 1000:1000
+        # Команда, которая будет запущена при старте контейнера java -jar ./app.jar
+        ENTRYPOINT ["java", "-jar", "/app.jar"]
     environment:
       SERVICE_PORT: 8081
       DB_URL: jdbc:postgresql://postgres:5432/memowave_db
@@ -107,13 +97,13 @@ services:
       DB_PASSWORD: pgadmin
     ports:
       - "8081:8081"
-    restart: unless-stopped
-    healthcheck:
-      test: [ "CMD", "curl", "-f", "http://user-management-service:8081/actuator/health" ]
-      interval: 10s
-      timeout: 5s
-      retries: 5
-      start_period: 10s
+#    restart: unless-stopped
+#    healthcheck:
+#      test: [ "CMD", "curl", "-f", "http://user-management-service:8081/actuator/health" ]
+#      interval: 10s
+#      timeout: 5s
+#      retries: 5
+#      start_period: 10s
     networks:
       - memowave-network
     depends_on:
@@ -123,43 +113,33 @@ services:
   gateway:
     container_name: gateway-service
     build:
-      dockerfile: module-gateway/Dockerfile
-#      dockerfile_inline: |
-#        # Родительский образ контейнера с gradle внутри
-#        FROM gradle:jdk21-alpine AS build
-#        LABEL authors="viktor"
-#        COPY . /app
-#        WORKDIR /app
-#        RUN gradle clean build --no-daemon
-#
-#        # Родительский образ контейнера с java внутри
-#        FROM eclipse-temurin:21-jre-alpine-3.22 AS run
-#        LABEL authors="viktor"
-#        RUN mkdir /app
-#        WORKDIR /app
-#        # Копирование jar-файла в контейнер
-#        COPY --from=build /app/module-gateway/build/libs/*-0.0.1-SNAPSHOT.jar /app.jar
-#        RUN apk add --no-cache curl
-#        # Открытие порта 8080
-#        EXPOSE 8080
-#        USER 1000:1000
-#        # Команда, которая будет запущена при старте контейнера java -jar ./app.jar
-#        ENTRYPOINT ["java", "-jar", "/app.jar"]
-    depends_on:
-      userservice:
-        condition: service_healthy
+      dockerfile_inline: |
+        # Родительский образ контейнера с java внутри
+        FROM eclipse-temurin:21-jre-alpine
+        RUN mkdir /app
+        WORKDIR /app
+        # Копирование jar-файла в контейнер
+        COPY module-gateway/build/libs/*-0.0.1-SNAPSHOT.jar /app.jar
+        # Открытие порта 8080
+        EXPOSE 8080
+        USER 1000:1000
+        # Команда, которая будет запущена при старте контейнера java -jar ./app.jar
+        ENTRYPOINT ["java", "-jar", "/app.jar"]
+#    depends_on:
+#      userservice:
+#        condition: service_healthy
     environment:
       SERVICE_PORT: 8080
       USER_MANAGEMENT_URL: "http://user-management-service:8081"
     ports:
       - "8080:8080"
-    restart: unless-stopped
-    healthcheck:
-      test: [ "CMD", "curl", "-f", "http://gateway-service:8080/actuator/health" ]
-      interval: 10s
-      timeout: 5s
-      retries: 5
-      start_period: 10s
+#    restart: unless-stopped
+#    healthcheck:
+#      test: [ "CMD", "curl", "-f", "http://gateway-service:8080/actuator/health" ]
+#      interval: 10s
+#      timeout: 5s
+#      retries: 5
+#      start_period: 10s
     networks:
       - memowave-network
 
